FROM node as builder
RUN mkdir /app
WORKDIR /app
COPY ./build ./build

FROM nginx:1.13.9-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d
RUN mkdir /app
COPY --from=builder /app /app
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
